GET http://localhost:3005/books HTTP/1.1
Coontent-Type: application/json

###

POST http://localhost:3005/books HTTP/1.1
Coontent-Type: application/json

{
    "title": "Harry Potter 3"
}

###

PUT http://localhost:3005/books/2 HTTP/1.1
Coontent-Type: application/json

{
    "title": "Harry Potter 3"
}